# OctoCoder model, 15B parameters, max_seq_length 8K
# Based on: https://arxiv.org/abs/2308.07124

trainer:
  init:
    backend:
      backend_type: CSX
    seed: 1
    model:
      name: "starcoder"
      # Embedding
      vocab_size: 49152
      position_embedding_type: learned
      embedding_dropout_rate: 0.1
      share_embedding_weights: true  # no config default values, HF uses tie_weights as default
      # Decoder Block
      hidden_size: 6144
      filter_size: 24576
      num_heads: 48
      num_hidden_layers: 40
      max_position_embeddings: 8192
      attention_module: multiquery_attention
      attention_type: scaled_dot_product
      attention_softmax_fp32: true
      scale_qk_dot_by_layer_idx: false
      extra_attention_params:
        num_kv_groups: 1
      use_projection_bias_in_attention: true
      use_ffn_bias_in_attention: true
      use_ffn_bias: true
      nonlinearity: gelu
      attention_dropout_rate: 0.1
      dropout_rate: 0.1
      layer_norm_epsilon: 1.0e-05
      use_bias_in_output: false
      initializer_range: 0.02
      loss_scaling: num_tokens
      output_layer_initializer:
        name: truncated_normal
        mean: 0.0
        std: 0.00223606797  # initializer_range / sqrt(2 * num_hidden_layers)
        a: -0.00447213595
        b: 0.00447213595
    optimizer:
      adam:
        betas:
        - 0.9
        - 0.95
        eps: 1.0e-08
        weight_decay: 0.1
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            total_iters: 56888
            initial_learning_rate: 0.0
            end_learning_rate: 0.0003
        - CosineDecayLR:
            initial_learning_rate: 0.0003
            total_iters: 6724779
            end_learning_rate: 3.0e-05
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    loop:
      max_steps: 6781667
      eval_frequency: 5000
    checkpoint:
      steps: 5000
    logging:
      log_steps: 100
  fit:
    train_dataloader:
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./shuffled/starcoder_data_test/val
      # The effective batch size, which is evenly divided across "num_csx" systems used for the run
      batch_size: 18
      shuffle: false
      shuffle_seed: 1
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader: &val_dataloader
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./shuffled/starcoder_data_test/test
      batch_size: 18
      shuffle: false
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
