# LLaMa model, 32.5B parameters, max_seq_length 2048
# Based on: https://arxiv.org/pdf/2302.13971v1.pdf

trainer:
  init:
    backend:
      backend_type: CSX
    model_dir: ./model_dir
    seed: 1
    model:
      name: "llama"
      # Embedding
      vocab_size: 32000
      hidden_size: 6656
      position_embedding_type: rotary
      rotary_dim: 128
      share_embedding_weights: false
      max_position_embeddings: 2048
      embedding_dropout_rate: 0.0
      norm_type: rmsnorm
      # Decoder
      num_hidden_layers: 60
      dropout_rate: 0.0
      layer_norm_epsilon: 1.0e-06
      # Decoder - Attention
      num_heads: 52
      attention_type: scaled_dot_product
      attention_dropout_rate: 0.0
      use_projection_bias_in_attention: false
      use_ffn_bias_in_attention: false
      # Decoder - ffn
      filter_size: 17888
      nonlinearity: swiglu
      use_ffn_bias: false
      # Task-specific
      use_bias_in_output: false
      loss_scaling: num_tokens
      loss_weight: 1.0
      # Cerebras parameters
      fp16_type: cbfloat16
      mixed_precision: true
    optimizer:
      AdamW:
        betas:
        - 0.9
        - 0.95
        correct_bias: true
        weight_decay: 0.1
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            end_learning_rate: 2.69e-05 # sqrt(batch_size / 2048) * 1.5e-4
            total_iters: 59362
        - CosineDecayLR:
            initial_learning_rate: 2.69e-05 # sqrt(batch_size / 2048) * 1.5e-4
            end_learning_rate: 2.69e-06 # sqrt(batch_size / 2048) * 1.5e-5
            total_iters: 9847793
    precision:
      enabled: true
      # Cerebras parameters
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    loop:
      max_steps: 10357481 # Llama 33B was trained on 1.4T tokens. # steps = 1.4T / (batch_size * 2048)
      eval_frequency: 10000
      eval_steps: 4404
    checkpoint:
      steps: 10000
      save_initial_checkpoint: true
    logging:
      # steps = 1.4T / (batch_size * 2048)
      log_steps: 100
    callbacks:
    - GlobalFlags:
        csx.debug.compile_crd_memory_gi: 67
  fit:
    train_dataloader:
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./shuffled/llama_data_test/val
      shuffle: false
      shuffle_seed: 1
      batch_size: 66
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader: &val_dataloader
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./shuffled/llama_data_test/test
      shuffle: false
      shuffle_seed: 1
      batch_size: 66
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
