# LLaMa model, 7B parameters, max_seq_length 2048
# Based on: https://arxiv.org/pdf/2302.13971v1.pdf

trainer:
  init:
    backend:
      backend_type: CSX
    model_dir: ./model_dir
    seed: 1
    model:
      name: "llama"
      # Embedding
      vocab_size: 32000
      hidden_size: 4096
      position_embedding_type: rotary
      rotary_dim: 128
      share_embedding_weights: false
      max_position_embeddings: 2048
      embedding_dropout_rate: 0.0
      # Decoder
      num_hidden_layers: 32
      dropout_rate: 0.0
      layer_norm_epsilon: 1.0e-06
      norm_type: rmsnorm
      # Decoder - Attention
      num_heads: 32
      attention_type: scaled_dot_product
      attention_dropout_rate: 0.0
      use_projection_bias_in_attention: false
      use_ffn_bias_in_attention: false
      # Decoder - ffn
      filter_size: 11008
      nonlinearity: swiglu
      use_ffn_bias: false
      # Task-specific
      use_bias_in_output: false
      loss_scaling: num_tokens
      loss_weight: 1.0
      # Cerebras parameters
      fp16_type: cbfloat16
      mixed_precision: true
    optimizer:
      AdamW:
        betas:
        - 0.9
        - 0.95
        correct_bias: true
        weight_decay: 0.1
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            end_learning_rate: 6.6e-05 # sqrt(batch_size / 2048) * 3.0e-4
            total_iters: 41373
        - CosineDecayLR:
            initial_learning_rate: 6.6e-05 # sqrt(batch_size / 2048) * 3.0e-4
            end_learning_rate: 6.6e-06 # sqrt(batch_size / 2048) * 3.0e-5
            total_iters: 4890748
    precision:
      enabled: true
      # Cerebras parameters
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    loop:
      max_steps: 4932121 # Llama 7B was trained on 1T tokens. # steps = 1T / (batch_size * 2048)
      eval_frequency: 10000
      eval_steps: 2974 # 294569 // batch_size - 1
    checkpoint:
      steps: 10000
      save_initial_checkpoint: true
    logging:
      # steps = 1T / (batch_size * 2048)
      log_steps: 100
  fit:
    train_dataloader:
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./shuffled/llama_data_test/val
      shuffle: false
      shuffle_seed: 1
      batch_size: 99
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader: &val_dataloader
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./shuffled/llama_data_test/test
      shuffle: false
      shuffle_seed: 1
      batch_size: 99
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
