# A 590M parameter Cerebras-GPT model configuration designed for a single CS-2

trainer:
  init:
    backend:
      backend_type: CSX
    model:
      name: "gpt3"
      # Embedding
      hidden_size: 1536
      position_embedding_type: learned
      share_embedding_weights: true
      max_position_embeddings: 2048
      vocab_size: 50257
      # Decoder
      num_hidden_layers: 18
      dropout_rate: 0.0
      layer_norm_epsilon: 1.0e-05  # change to 1.0e-12 for single precision training
      # Decoder - Attention
      num_heads: 12
      attention_type: scaled_dot_product
      attention_dropout_rate: 0.0
      use_projection_bias_in_attention: true
      use_ffn_bias_in_attention: true
      # Decoder - ffn
      filter_size: 6144
      nonlinearity: gelu
      use_ffn_bias: true
      embedding_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.08
        a: -0.16
        b: 0.16
      initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.08
        a: -0.16
        b: 0.16
      output_layer_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.08
        a: -0.16
        b: 0.16
      # Task-specific
      loss_scaling: batch_size    # needed for gradient accumulation
      loss_weight: 0.00048828125  # = 1/max_sequence_length
      use_bias_in_output: false
      # muP
      mup_base_filter_size: 1024
      mup_base_hidden_size: 256
      scale_qk_dot_by_d: true
      output_logits_alpha: 1.0
      embeddings_scale: 10
    optimizer:
      AdamW:
        betas:
        - 0.9
        - 0.95
        eps: 1.0e-08
        weight_decay: 0.1
        correct_bias: true
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            end_learning_rate: 0.006
            total_iters: 693
        - LinearLR:
            initial_learning_rate: 0.006
            end_learning_rate: 0.0006
            total_iters: 21143
    precision:
      # Cerebras parameters
      enabled: true
      fp16_type: bfloat16
      precision_opt_level: 0  # also validated with precision_opt_level = 1
      max_gradient_norm: 1.0
      log_loss_scale: true
    loop:
      max_steps: 21836
      eval_frequency: 2183
      eval_steps: 702
    checkpoint:
      steps: 2183
      save_initial_checkpoint: false
    logging:
      log_steps: 1
    callbacks:
    - ComputeNorm: {}
  fit:
    train_dataloader:
      data_processor: GptHDF5DataProcessor
      data_dir:
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/0/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/1/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/2/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/3/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/4/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/5/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/6/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/7/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/8/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/9/
      shuffle: true
      shuffle_seed: 0
      # The effective batch size, which is evenly divided across "num_csx" systems used for the run
      batch_size: 264  # 264 global = (264 micro)*(1 csx)*(1 grad accum step)
      num_workers: 1
      prefetch_factor: 10
      persistent_workers: true  # Important to avoid seeding at each epoch
    val_dataloader: &val_dataloader
      data_processor: GptHDF5DataProcessor
      data_dir: ./language/datasets/pile_original/hdf5_dataset/val_msl2048/
      batch_size: 264
      shuffle: false
      num_workers: 1
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
