# GPT-J 6B model
# reference: https://github.com/kingoflolz/mesh-transformer-jax/blob/master/configs/6B_roto_256.json

trainer:
  fit:
    train_dataloader:
      batch_size: 120
      data_dir:
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/0/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/1/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/2/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/3/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/4/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/5/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/6/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/7/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/8/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/9/
      data_processor: GptHDF5MapDataProcessor
      num_workers: 8
      persistent_workers: true
      prefetch_factor: 10
      shuffle: false
      shuffle_seed: 1337
    val_dataloader: &val_dataloader
      # The effective batch size, which is evenly divided across "num_csx" systems used for the run
      batch_size: 120
      data_dir: ./language/datasets/pile_original/hdf5_dataset/val_msl2048/
      data_processor: GptHDF5MapDataProcessor
      num_workers: 8
      persistent_workers: true # Important to avoid seeding at each epoch
      prefetch_factor: 10
      shuffle: false
  init:
    backend:
      backend_type: CSX
    checkpoint:
      steps: 10000
    logging:
      log_steps: 100
    loop:
      eval_frequency: 10000
      max_steps: 1493333 # 350000 * 512 / 120
    model:
      name: "gptj"
      attention_dropout_rate: 0.0
      attention_logits_alpha: 4.0
      attention_type: scaled_dot_product
      embedding_dropout_rate: 0.0
      # Initializer references: https://github.com/kingoflolz/mesh-transformer-jax/blob/master/mesh_transformer/layers.py
      # We use truncated_normal instead of normal ("ref: https://github.com/kingoflolz/mesh-transformer-jax"),
      # with the same std and mean for better performance
      embedding_initializer:
        a: -0.00892137336
        b: 0.00892137336
        mean: 0.0
        name: truncated_normal
        std: 0.00446068668 # 1 / sqrt(vocab_size)
      embeddings_scale: 14.6
      filter_size: 16384 # 4 * hidden_size
      hidden_size: 4096
      initializer:
        a: -2.0
        b: 2.0
        mean: 0.0
        name: truncated_normal
        std: 1.0
      initializer_range: 0.02
      layer_norm_epsilon: 1.0e-05
      loss_scaling: num_tokens
      loss_weight: 1.0
      max_position_embeddings: 2048
      mup_base_filter_size: 8192
      mup_base_hidden_size: 2048
      nonlinearity: gelu
      num_heads: 16
      num_hidden_layers: 28
      output_layer_initializer:
        a: -0.14285714285714285
        b: 0.14285714285714285
        mean: 0.0
        name: truncated_normal
        std: 0.07142857142857142 # 2 / num_hidden_layers
      output_logits_alpha: 2.22
      position_embedding_type: rotary
      residual_dropout_rate: 0.0
      rotary_dim: 64 # hidden_size / num_heads * 25%
      scale_qk_dot_by_d: true
      share_embedding_weights: false
      use_bias_in_output: true
      use_ffn_bias: true
      use_ffn_bias_in_attention: false
      use_projection_bias_in_attention: false
      vocab_size: 50257
    optimizer:
      adamw:
        correct_bias: true
        eps: 1.0e-06
        weight_decay: 0.1
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    schedulers:
    - SequentialLR:
        schedulers:
        # we want to keep the same number of tokens consistent with Eleuther gptj-6B
        # Eleuther batch_size https://github.com/kingoflolz/mesh-transformer-jax/blob/master/train.py#L89-L94
        # Eleuther 6B config https://github.com/kingoflolz/mesh-transformer-jax/blob/master/configs/6B_roto_256.json
        # Eleuther gpt-j: steps * batch_size (512) * seq_len (2048)
        - LinearLR:
            end_learning_rate: 5.809e-05 # sqrt(120 / 512) * 1.2e-4
            initial_learning_rate: 0.0
            total_iters: 12800 # 3000 * 512 / 120
        - CosineDecayLR:
            end_learning_rate: 5.809e-06 # sqrt(120 / 512) * 1.2e-5
            initial_learning_rate: 5.809e-05
            total_iters: 1280000 # 300000 * 512 / 120
        - ConstantLR:
            learning_rate: 5.809e-06
    seed: 1
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
