trainer:
  fit:
    train_dataloader:
      batch_size: 24
      data_dir: ./datasets/mle_datasets/wiki_en_100k_gemma2_msl8k_train/
      data_processor: GptHDF5MapDataProcessor
      num_workers: 8
      persistent_workers: true
      prefetch_factor: 10
      shuffle: true
      shuffle_seed: 1337
      vocab_size: 256000
    val_dataloader: &id001
      batch_size: 24
      data_dir: ./datasets/mle_datasets/wiki_en_10k_gemma2_msl8k_val/
      data_processor: GptHDF5MapDataProcessor
      num_workers: 8
      shuffle: false
      vocab_size: 256000
  init:
    backend:
      backend_type: CSX
    callbacks:
    - ComputeNorm: {}
    - LoadCheckpointStates:
        load_checkpoint_states: model
    checkpoint:
      disable_strict_checkpoint_loading: true
      save_initial_checkpoint: false
      steps: 85
    logging:
      log_steps: 1
    loop:
      eval_steps: 15
      max_steps: 170
    model:
      name: gemma2
      attention_dropout_rate: 0.0
      attention_inner_dim: 4096
      attention_logit_softcapping: 50.0
      attention_module: multiquery_attention
      attention_sliding_window_length: 4096
      dropout_rate: 0.0
      embeddings_scale: 59.8665181
      extra_attention_params:
        num_kv_groups: 8
      filter_size: 14336
      final_logit_softcapping: 30.0
      hidden_size: 3584
      layer_norm_epsilon: 1.0e-06
      max_position_embeddings: 8192
      nonlinearity: geglu
      norm_first_sandwich: true
      norm_type: rmsnorm
      num_heads: 16
      num_hidden_layers: 42
      position_embedding_type: rotary
      rope_theta: 10000.0
      rotary_dim: 256
      share_embedding_weights: true
      sliding_window_every_other_decoder_layer: true
      use_ffn_bias: false
      use_ffn_bias_in_attention: false
      use_projection_bias_in_attention: false
      vocab_size: 256000
    optimizer:
      AdamW:
        betas:
        - 0.9
        - 0.95
        correct_bias: true
        weight_decay: 0.1
    precision:
      enabled: true
      log_loss_scale: true
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    schedulers:
    - SequentialLR:
        schedulers:
        - CosineDecayLR:
            end_learning_rate: 0.0001
            initial_learning_rate: 0
            total_iters: 10
        - CosineDecayLR:
            end_learning_rate: 1.0e-05
            initial_learning_rate: 0.0001
            total_iters: 160
    seed: 1
  validate:
    val_dataloader: *id001
  validate_all:
    val_dataloaders: *id001
