# Gemma2 model, 27B parameters, max_seq_length 8192

trainer:
  init:
    seed: 1
    model:
      name: gemma2
      attention_dropout_rate: 0.0
      attention_inner_dim: 4096
      attention_logit_softcapping: 50.0
      attention_logits_alpha: 0.9428090415820634
      attention_module: multiquery_attention
      attention_sliding_window_length: 4096
      dropout_rate: 0.0
      embeddings_scale: 67.8822509
      extra_attention_params:
        num_kv_groups: 16
      filter_size: 36864
      final_logit_softcapping: 30.0
      hidden_size: 4608
      layer_norm_epsilon: 1.0e-06
      max_position_embeddings: 8192
      norm_first_sandwich: true
      nonlinearity: geglu
      norm_type: rmsnorm
      num_heads: 32
      num_hidden_layers: 46
      position_embedding_type: rotary
      rope_theta: 10000.0
      rotary_dim: 128
      share_embedding_weights: true
      sliding_window_every_other_decoder_layer: true
      use_ffn_bias_in_attention: false
      use_projection_bias_in_attention: false
      use_ffn_bias: false
      vocab_size: 256000
    optimizer:
      AdamW:
        betas:
        - 0.9
        - 0.95
        correct_bias: true
        weight_decay: 0.1
    schedulers:
    - SequentialLR:
        schedulers:
        - CosineDecayLR:
            initial_learning_rate: 0
            end_learning_rate: 5.0e-05
            total_iters: 10
        - CosineDecayLR:
            initial_learning_rate: 5.0e-05
            end_learning_rate: 5.0e-06
            total_iters: 160
    precision:
      enabled: true
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
      log_loss_scale: true
    loop:
      # loss valid tokens: 110784565; max_steps = 110784565/(8192*80)
      max_steps: 170
      # loss valid tokens: 9828790; eval_steps = 9828790 / (8192*80)
      eval_steps: 15
    checkpoint:
      steps: 85
      disable_strict_checkpoint_loading: true
      save_initial_checkpoint: false
    logging:
      log_steps: 1
    backend:
      backend_type: CSX
    callbacks:
    - GlobalFlags:
        csx.debug.execute_crd_memory_gi: 45
    - ScopedTrainFlags:
        csx.performance.micro_batch_size: 9
    - ScopedValidateFlags:
        csx.performance.micro_batch_size: 9
    - ComputeNorm: {}
  fit:
    train_dataloader:
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./datasets/mle_datasets/wiki_en_100k_gemma2_msl8k_train/    # Colo
      vocab_size: 256000
      # The effective batch size, which is evenly divided across "num_csx" systems used for the run
      batch_size: 9
      shuffle: true
      shuffle_seed: 1337
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true  # Important to avoid seeding at each epoch
    val_dataloader: &val_dataloader
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./datasets/mle_datasets/wiki_en_10k_gemma2_msl8k_val/
      vocab_size: 256000
      batch_size: 9
      shuffle: false
      num_workers: 8
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
