trainer:
  init:
    model_dir: ./model_dir
    seed: 1
    model:
      name: mistral
      vocab_size: 131072
      hidden_size: 5120
      attention_inner_dim: 4096
      position_embedding_type: rotary
      rotary_dim: 128
      rope_theta: 1000000.0
      share_embedding_weights: false
      max_position_embeddings: 131072
      embedding_dropout_rate: 0.0
      num_hidden_layers: 40
      dropout_rate: 0.0
      layer_norm_epsilon: 1.0e-05
      norm_type: rmsnorm
      num_heads: 32
      attention_type: scaled_dot_product
      attention_module: multiquery_attention
      extra_attention_params:
        num_kv_groups: 8
      attention_dropout_rate: 0.0
      use_projection_bias_in_attention: false
      use_ffn_bias_in_attention: false
      filter_size: 14336
      nonlinearity: swiglu
      use_ffn_bias: false
      use_bias_in_output: false
    optimizer:
      AdamW:
        betas:
        - 0.9
        - 0.95
        correct_bias: true
        weight_decay: 0.1
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            end_learning_rate: 6.0e-07
            total_iters: 4
        - CosineDecayLR:
            initial_learning_rate: 6.0e-07
            end_learning_rate: 3.87e-08
            total_iters: 305
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    loop:
      max_steps: 309
      eval_frequency: 50
      eval_steps: 10
    checkpoint:
      steps: 150
      save_initial_checkpoint: true
    logging:
      log_steps: 1
    callbacks:
    - ScopedTrainFlags:
        csx.performance.micro_batch_size: 1
    - ScopedValidateFlags:
        csx.performance.micro_batch_size: 2
    backend:
      backend_type: CSX
  fit:
    train_dataloader:
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./datasets/rpj_1t/rpj_1t_100k_mistralnemo_msl128k_train
      vocab_size: 131072
      batch_size: 32
      shuffle: true
      shuffle_seed: 1337
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader: &id001
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./datasets/rpj_1t/rpj_1t_100k_mistralnemo_msl128k_val
      vocab_size: 131072
      batch_size: 32
      shuffle: false
      num_workers: 8
  validate:
    val_dataloader: *id001
  validate_all:
    val_dataloaders: *id001
