trainer:
  init:
    seed: 1
    backend:
      cluster_config:
        num_workers_per_csx: 2
      backend_type: CSX
      csx.debug.implicit_cast_cb16_to_fp32: True
    model:
      name: vision_transformer
      num_classes: 1000
      position_embedding_type: learned
      embedding_dropout_rate: 0.1
      hidden_size: 768
      num_hidden_layers: 12
      layer_norm_epsilon: 1.0e-06
      num_heads: 12
      attention_type: scaled_dot_product
      attention_softmax_fp32: true
      dropout_rate: 0.1
      nonlinearity: gelu
      pooler_nonlinearity: tanh
      attention_dropout_rate: 0.1
      use_projection_bias_in_attention: true
      use_ffn_bias_in_attention: true
      filter_size: 3072
      use_ffn_bias: true
      initializer_range: 0.02
      norm_first: true
      image_size:
      - 224
      - 224
      num_channels: 3
      patch_size:
      - 16
      - 16
      use_conv_patchified_embedding: true
      use_encoder_pooler_layer: false
      prepend_cls_token: true
    optimizer:
      Adam:
        betas:
        - 0.9
        - 0.999
        eps: 1.0e-08
        weight_decay: 0.0003
        correct_bias: true
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            end_learning_rate: 0.0005
            total_iters: 14371
        - CosineDecayLR:
            initial_learning_rate: 0.0005
            end_learning_rate: 0.0
            total_iters: 117854
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    loop:
      max_steps: 132225
      eval_frequency: 1000
    checkpoint:
      steps: 1000
    logging:
      log_steps: 1
    callbacks:
    - ScopedTrainFlags:
        csx.performance.micro_batch_size: 2850
    - ScopedValidateFlags:
        csx.performance.micro_batch_size: 2850
  fit:
    train_dataloader:
      data_processor: ImageNet1KProcessor
      data_dir: ./computer_vision/datasets/imagenet/imagenet1k_ilsvrc2012
      num_classes: 1000
      batch_size: 2850
      image_size:
      - 224
      - 224
      shuffle: true
      shuffle_seed: 42
      split: train
      transforms:
      - name: resize
        size:
        - 256
        - 256
      - name: random_resized_crop
        size:
        - 224
        - 224
        scale:
        - 0.08
        - 1.0
        ratio:
        - 0.75
        - 1.33
        interpolation: bilinear
      - name: random_horizontal_flip
        p: 0.5
      - name: to_tensor
      - name: normalize
        mean:
        - 0.5
        - 0.5
        - 0.5
        std:
        - 0.5
        - 0.5
        - 0.5
      num_workers: 2
      prefetch_factor: 2
      persistent_workers: true
      use_worker_cache: true
    val_dataloader: &id001
      data_processor: ImageNet1KProcessor
      data_dir: ./computer_vision/datasets/imagenet/imagenet1k_ilsvrc2012
      num_classes: 1000
      batch_size: 2850
      image_size:
      - 224
      - 224
      shuffle: false
      shuffle_seed: 42
      split: val
      transforms:
      - name: resize
        size:
        - 224
        - 224
      - name: to_tensor
      - name: normalize
        mean:
        - 0.5
        - 0.5
        - 0.5
        std:
        - 0.5
        - 0.5
        - 0.5
      num_workers: 2
      prefetch_factor: 2
      persistent_workers: true
      use_worker_cache: true
  validate:
    val_dataloader: *id001
  validate_all:
    val_dataloaders: *id001
