# GPT-J 6B model
# Based on src/models/transformers/tf/gptj/configs/params_gptj_6B.yaml

train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./language/datasets/model_studio/TRC2/gpt2-tokenized/train"
    vocab_size: 50400
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 56 # reduced from 64 should give us ~17K steps for 1 epoch
    shuffle: True
    shuffle_seed: 1337
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./language/datasets/model_studio/TRC2/gpt2-tokenized/eval"
    vocab_size: 50400
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 64
    shuffle: False
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

model:
    # Embedding
    vocab_size: 50400 
    position_embedding_type: "rotary"
    embedding_dropout_rate: 0.0
    share_embedding_weights: False

    # Decoder Block
    hidden_size: 4096
    num_heads: 16
    num_hidden_layers: 28
    max_position_embeddings: 512
    attention_type: "scaled_dot_product"

    use_projection_bias_in_attention: False
    use_ffn_bias_in_attention: False
    use_ffn_bias: True

    filter_size: 16384
    nonlinearity: "gelu"
    attention_dropout_rate: 0.0
    residual_dropout_rate: 0.0

    rotary_dim: 64
    layer_norm_epsilon: 1.0e-5
    use_bias_in_output: True
    initializer_range: 0.02

    loss_scaling: "num_tokens"

    embedding_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.00446068668 # 1 / sqrt(vocab_size)

    initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.015625 # 1 / sqrt(hidden_size)

    output_layer_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.00111607142 # 2 / num_hidden_layers / sqrt(hidden_size)

    fp16_type: "cbfloat16"
    mixed_precision: True

optimizer:
    optimizer_type: "adamw"
    eps: 1.0e-6
    weight_decay: 0.1
    max_gradient_norm: 1.0
    correct_bias: True
    learning_rate:
      - scheduler: "Linear"
        initial_learning_rate: 0.0
        end_learning_rate: 6.0e-6
        total_iters: 500
      - scheduler: "CosineDecay"
        initial_learning_rate: 6.0e-6
        end_learning_rate: 1.2e-6
        total_iters: 50000
      - scheduler: "Constant"
        learning_rate: 1.2e-6
    loss_scaling_factor: "dynamic"

runconfig:
    max_steps: 25000
    log_steps: 50
    checkpoint_steps: 1000
    seed: 1
