trainer:
  init:
    seed: 1
    model:
      name: gptj
      vocab_size: 50400
      position_embedding_type: rotary
      embedding_dropout_rate: 0.0
      share_embedding_weights: false
      hidden_size: 4096
      num_heads: 16
      num_hidden_layers: 28
      max_position_embeddings: 512
      attention_type: scaled_dot_product
      use_projection_bias_in_attention: false
      use_ffn_bias_in_attention: false
      use_ffn_bias: true
      filter_size: 16384
      nonlinearity: gelu
      attention_dropout_rate: 0.0
      residual_dropout_rate: 0.0
      rotary_dim: 64
      layer_norm_epsilon: 1e-05
      use_bias_in_output: true
      initializer_range: 0.02
      loss_scaling: num_tokens
      embedding_initializer:
        name: truncated_normal
        mean: 0.0
        std: 0.00446068668
      initializer:
        name: truncated_normal
        mean: 0.0
        std: 0.015625
      output_layer_initializer:
        name: truncated_normal
        mean: 0.0
        std: 0.00111607142
    optimizer:
      adamw:
        eps: 1e-06
        weight_decay: 0.1
        correct_bias: true
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            end_learning_rate: 6e-06
            total_iters: 500
        - CosineDecayLR:
            initial_learning_rate: 6e-06
            end_learning_rate: 1.2e-06
            total_iters: 50000
        - ConstantLR:
            learning_rate: 1.2e-06
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    loop:
      max_steps: 25000
    checkpoint:
      steps: 1000
    logging:
      log_steps: 50
  fit:
    train_dataloader:
      data_processor: GptHDF5DataProcessor
      data_dir: ./language/datasets/model_studio/TRC2/gpt2-tokenized/train
      vocab_size: 50400
      batch_size: 56
      shuffle: true
      shuffle_seed: 1337
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader: &id001
      data_processor: GptHDF5DataProcessor
      data_dir: ./language/datasets/model_studio/TRC2/gpt2-tokenized/eval
      vocab_size: 50400
      batch_size: 64
      shuffle: false
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
  validate:
    val_dataloader: *id001
  validate_all:
    val_dataloaders: *id001
