dataset:
  name: zwhe99/DeepMath-103K
  split: train
  sample_size: 50

embedding_model:
  path: ./SFR-Embedding-Code-400M_R
  trust_remote_code: true
  download_url: https://huggingface.co/SFR-Embedding/SFR-Embedding-Code-400M/resolve/main/SFR-Embedding-Code-400M_R.zip

zero_shot_model:
  name: valhalla/distilbart-mnli-12-9
  device: -1

language_detection_model:
  path: lid.176.ftz
  download_url: https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.ftz

clustering_attributes:
  min_cluster_size: 2

classification_attributes:
  candidate_labels:
    - Adult
    - Arts_and_Entertainment
    - Autos_and_Vehicles
    - Beauty_and_Fitness
    - Books_and_Literature
    - Business_and_Industrial
    - Computers_and_Electronics
    - Finance
    - Food_and_Drink
    - Games
    - Health
    - Hobbies_and_Leisure
    - Home_and_Garden
    - Internet_and_Telecom
    - Jobs_and_Education
    - Law_and_Government
    - Mathematics
    - News
    - Online_Communities
    - People_and_Society
    - Pets_and_Animals
    - Real_Estate
    - Science
    - Sensitive_Subjects
    - Shopping
    - Sports
    - Travel_and_Transportation
