#BERT-SST2-Large

train_input:
    data_processor: "SST2DataProcessor"
    data_dir: "./language/datasets/glue_data/SST-2"
    vocab_file: "../../../../vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 72
    do_lower: True
    batch_size: 12
    num_workers: 8
    shuffle: True
    shuffle_seed: 1

eval_input:
    data_processor: "SST2DataProcessor"
    data_dir: "./language/datasets/glue_data/SST-2"
    vocab_file: "../../../../vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 72
    do_lower: True
    batch_size: 12
    num_workers: 1
    shuffle: False
    shuffle_seed: 1

model:
    vocab_size: 30522
    hidden_size: 1024
    num_hidden_layers: 24
    num_heads: 16
    filter_size: 4096
    encoder_nonlinearity: "gelu" # {"gelu", "relu", "silu", "gelu_new"}
    dropout_rate: 0.1
    attention_dropout_rate: 0.1
    max_position_embeddings: 512
    task_dropout: 0.1
    problem_type: "single_label_classification"
    num_labels: 2
    mixed_precision: True
    compute_eval_metrics: True

optimizer:
    optimizer_type: "AdamW"
    weight_decay_rate: 0.01
    epsilon: 1e-6
    max_gradient_norm: 1.0
    learning_rate:
        - scheduler: "Linear"
          steps: 2000
          initial_learning_rate: 0.0
          end_learning_rate: 0.000005
        - scheduler: "Constant"
          learning_rate: 0.000005
    loss_scaling_factor: "dynamic"
    log_summaries: True

runconfig:
    max_steps: 20000 # ~3 epochs, 67k samples in an epoch
    log_steps: 1000
    save_summary_steps: 100
    checkpoint_steps: 5000
    seed: 1
    show_debug_metrics: False
    save_losses: True
    model_dir: "./model_dir"
    save_initial_checkpoint: True
    eval_steps: 71
