# LLaMa model, 7B parameters, max_seq_length 2048
# Based on: https://arxiv.org/pdf/2302.13971v1.pdf

train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./llama_data_test/val"
    shuffle: False
    shuffle_seed: 1
    batch_size: 2048
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./llama_data_test/test"
    shuffle: False
    shuffle_seed: 1
    batch_size: 2048
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

model:
    # Embedding
    vocab_size: 32000
    hidden_size: 4096
    use_position_embedding: True
    position_embedding_type: "rotary"
    rotary_dim: 128
    share_embedding_weights: False
    max_position_embeddings: 2048
    embedding_dropout_rate: 0.0

    # Decoder
    num_hidden_layers: 32
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-6
    use_rms_norm: True

    # Decoder - Attention
    num_heads: 32
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: False
    use_ffn_bias_in_attention: False

    # Decoder - ffn
    filter_size: 11008
    nonlinearity: "swiglu"
    use_ffn_bias: False

    # Task-specific
    use_bias_in_output: False
    loss_scaling: "batch_size"
    loss_weight: 0.000488281 # = 1/max_sequence_length

    # Cerebras parameters
    mixed_precision: True

optimizer:
    optimizer_type: "AdamW"
    beta1: 0.9
    beta2: 0.95
    correct_bias: True
    disable_lr_steps_reset: False
    weight_decay_rate: 0.01
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 3.0e-4
          steps: 2000
        - scheduler: "CosineDecay"
          initial_learning_rate: 3.0e-4
          end_learning_rate: 3.0e-5
          decay_steps: 999998000

runconfig:
    max_steps: 1000000000      # LLaMa 7B was pretrained to 1T steps
    log_steps: 100
    checkpoint_steps: 10000
    save_initial_checkpoint: True
    seed: 1
    model_dir: "./model_dir"
    show_debug_metrics: False
    save_losses: True
    eval_steps: 233
    use_cs_grad_accum: True
