# Falcon model, 180B parameters, MSL 2048
# Based on: https://huggingface.co/tiiuae/falcon-40b/tree/main

# NOTE:
# The only minor difference is that falcon tie dropout between mlp and attention_output
# on our implementation this is untied (2 dropouts)
# however, in the pretrained falcon model all dropout rates are set to be 0.0 so it is equivalent

trainer:
  init:
    backend:
      backend_type: CSX
    seed: 1
    model:
      name: "falcon"
      # Embedding
      vocab_size: 65024
      max_position_embeddings: 2048
      position_embedding_type: rotary
      rotary_dim: 64 # hidden_size / num_heads, falcon use 100% rotation, reference https//github.com/huggingface/transformers/blob/main/src/transformers/models/falcon/modeling_falcon.py#L294
      rope_theta: 10000.0
      embedding_dropout_rate: 0.0
      share_embedding_weights: true # no config default values, HF uses tie_weights as default
      # Decoder Block
      hidden_size: 14848
      filter_size: 59392
      num_heads: 232
      num_hidden_layers: 80
      attention_module: multiquery_attention
      attention_type: scaled_dot_product
      use_untied_layer_norm: true
      extra_attention_params:
        num_kv_groups: 8
      use_projection_bias_in_attention: false
      use_ffn_bias_in_attention: false
      use_ffn_bias: false
      nonlinearity: gelu
      attention_dropout_rate: 0.0
      residual_dropout_rate: 0.0
      layer_norm_epsilon: 1.0e-05
      use_bias_in_output: false
      initializer_range: 0.02
      loss_scaling: num_tokens
    optimizer:
      adamw:
        betas:
        - 0.9
        - 0.999
        eps: 1.0e-08
        weight_decay: 0.1
        correct_bias: true
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            total_iters: 28886 # 1% of max_steps
            initial_learning_rate: 0.0
            end_learning_rate: 0.00082158 # sqrt(batch_size / 16) * (6.0e-4)
        - CosineDecayLR:
            initial_learning_rate: 0.00082158
            total_iters: 2859752 # 2888638 - 28886
            end_learning_rate: 8.2158e-05 # (1 - 0.9) * 6.0e-4 * sqrt(batch_size / 16)
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    loop:
      max_steps: 2888638 # 5416198 * 16 / 30
      eval_frequency: 5000
    checkpoint:
      steps: 5000
    logging:
      log_steps: 100
    callbacks:
    - GlobalFlags:
        csx.debug.compile_crd_memory_gi: 67
        csx.debug.execute_crd_memory_gi: 50
  fit:
    train_dataloader:
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./shuffled/falcon_data_test/val
      shuffle: false
      shuffle_seed: 1
      batch_size: 30
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader: &val_dataloader
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./shuffled/falcon_data_test/test
      shuffle: false
      shuffle_seed: 1
      batch_size: 30
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
