#BERT-SST2-Base

trainer:
  init:
    backend:
      backend_type: CSX
    model_dir: ./model_dir
    seed: 1
    model:
      name: "bert/classifier"
      vocab_size: 30522
      hidden_size: 768
      num_hidden_layers: 12
      num_heads: 12
      filter_size: 3072
      encoder_nonlinearity: gelu # {"gelu", "relu", "silu", "gelu_new"}
      pooler_nonlinearity: tanh
      dropout_rate: 0.1
      attention_dropout_rate: 0.1
      max_position_embeddings: 512
      task_dropout: 0.1
      problem_type: single_label_classification
      num_labels: 2
      compute_eval_metrics: false
    optimizer:
      AdamW:
        weight_decay: 0.01
        eps: 1.0e-06
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            total_iters: 2000
            initial_learning_rate: 0.0
            end_learning_rate: 1.0e-05
        - ConstantLR:
            learning_rate: 1.0e-05
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    loop:
      max_steps: 20000 # ~3 epochs, 67k samples in an epoch
      eval_frequency: 5000
      eval_steps: 71
    checkpoint:
      steps: 5000
      save_initial_checkpoint: true
    logging:
      log_steps: 1000
  fit:
    train_dataloader:
      data_processor: SST2DataProcessor
      is_training: True
      data_dir: ./language/datasets/glue_data/SST-2
      vocab_file: "$MODELZOO_ROOT/models/vocab/google_research_uncased_L-12_H-768_A-12.txt"
      max_sequence_length: 128
      # The effective batch size, which is evenly divided across "num_csx" systems used for the run
      batch_size: 4096
      shuffle: true
      shuffle_seed: 1
      num_workers: 8
      do_lower: true
    val_dataloader: &val_dataloader
      data_processor: SST2DataProcessor
      is_training: False
      data_dir: ./language/datasets/glue_data/SST-2
      vocab_file: ./language/models/bert/pretrained/google-research/uncased_L-12_H-768_A-12/vocab.txt
      max_sequence_length: 128
      batch_size: 12
      shuffle: false
      shuffle_seed: 1
      num_workers: 1
      do_lower: true
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
