# A 111M parameter Cerebras-GPT model config mu-transferred from the 40M base model.
# Optimal hyperparameters were determined in a hyperparameter sweep at 40M scale
# which were then mu-transferred to 111M model.

trainer:
  init:
    backend:
      backend_type: CSX
    model:
      name: "gpt3"
      vocab_size: 50257
      hidden_size: 768
      position_embedding_type: learned
      share_embedding_weights: true
      max_position_embeddings: 2048
      num_hidden_layers: 10
      dropout_rate: 0.0
      layer_norm_epsilon: 1.0e-05
      num_heads: 12
      attention_type: scaled_dot_product
      attention_dropout_rate: 0.0
      use_projection_bias_in_attention: true
      use_ffn_bias_in_attention: true
      filter_size: 3072
      nonlinearity: gelu
      use_ffn_bias: true
      embedding_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.08
        a: -0.16
        b: 0.16
      initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.08
        a: -0.16
        b: 0.16
      output_layer_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.08
        a: -0.16
        b: 0.16
      loss_scaling: num_tokens
      loss_weight: 1.0
      use_bias_in_output: false
      mup_base_filter_size: 1024
      mup_base_hidden_size: 256
      output_logits_alpha: 1.0
      embeddings_scale: 10.0
      scale_qk_dot_by_d: true
    optimizer:
      AdamW:
        # adjust_learning_rate:
        #   decoder_kernel: 0.3333333333333333
        betas: [0.9, 0.95]
        eps: 1.0e-08
        weight_decay: 0.1
        correct_bias: true
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            end_learning_rate: 0.006
            total_iters: 1525
        - LinearLR:
            initial_learning_rate: 0.006
            end_learning_rate: 0.0006
            total_iters: 7512
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
      log_loss_scale: true
    loop:
      max_steps: 9037
      eval_frequency: 903
      eval_steps: 1546
    checkpoint:
      steps: 903
      save_initial_checkpoint: false
    logging:
      log_steps: 1
    callbacks:
    - ComputeNorm: {}
  fit:
    train_dataloader:
      data_processor: GptHDF5MapDataProcessor
      data_dir:
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/0/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/1/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/2/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/3/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/4/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/5/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/6/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/7/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/8/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/9/
      shuffle: false # data is expected to be shuffled during preprocessing
      shuffle_seed: 0
      batch_size: 120
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader: &val_dataloader
      data_processor: GptHDF5DataProcessor
      data_dir: ./language/datasets/pile_original/hdf5_dataset/val_msl2048/
      batch_size: 120
      shuffle: false
      num_workers: 8
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
