trainer:
  init:
    model_dir: ./model_dir
    seed: 1
    backend:
      backend_type: CSX
      cluster_config:
        max_wgt_servers: 24
        num_workers_per_csx: 1
    model:
      name: "mixtral"
      # Embedding
      vocab_size: 32000
      hidden_size: 6144
      position_embedding_type: rotary
      rotary_dim: 128
      rope_theta: 1000000.0
      share_embedding_weights: false
      max_position_embeddings: 65536
      embedding_dropout_rate: 0.0
      # Decoder
      num_hidden_layers: 56
      dropout_rate: 0.0
      layer_norm_epsilon: 1.0e-05
      norm_type: rmsnorm
      # Decoder - Attention
      num_heads: 48
      attention_type: scaled_dot_product
      attention_module: multiquery_attention
      extra_attention_params:
        num_kv_groups: 8
      attention_dropout_rate: 0.0
      use_projection_bias_in_attention: false
      use_ffn_bias_in_attention: false
      # Decoder - ffn
      filter_size: 16384
      nonlinearity: swiglu
      use_ffn_bias: false
      moe:
        num_experts: 8
        top_k: 2
        load_balancing_loss_coef: 0.001
        router_fp32: true
      # Task-specific
      use_bias_in_output: false
    optimizer:
      AdamW:
        betas:
        - 0.9
        - 0.95
        correct_bias: true
        weight_decay: 0.1
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            end_learning_rate: 0.0003
            total_iters: 2000
        - CosineDecayLR:
            initial_learning_rate: 0.0003
            end_learning_rate: 3.0e-05
            total_iters: 236418
    precision:
      enabled: true
      # Cerebras parameters
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    loop:
      # We might want to adjust these later 
      max_steps: 238418
      eval_steps: 233
    checkpoint:
      steps: 10000
      save_initial_checkpoint: true
    logging:
      log_steps: 100
    callbacks:
    - ScopedTrainFlags:
        csx.performance.micro_batch_size: 1
    - ScopedValidateFlags:
        csx.performance.micro_batch_size: 1
  fit:
    train_dataloader:
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./datasets/long_msl/shuffled/mistral/msl_64k
      vocab_size: 32000
      batch_size: 256
      shuffle: true
      shuffle_seed: 1337
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true # Important to avoid seeding at each epoch
    val_dataloader: &val_dataloader
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./datasets/long_msl/shuffled/mistral/msl_64k
      vocab_size: 32000
      batch_size: 12
      shuffle: false
      num_workers: 8
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
