trainer:
    init:
        model_dir: ./model_dir
        seed: 1
        model:
            name: layers_api_demo
            vocab_size: 26
            embedding_size: 64
            num_heads: 2
            hidden_size: 64
            num_hidden_layers: 2
            dropout: 0.0
            seq_len: 10
            nonlinearity: gelu
            mixed_precision: true
        optimizer:
            Adam:
                correct_bias: true
                weight_decay: 0.01
        schedulers:
        -   LinearLR:
                initial_learning_rate: 0.0001
                end_learning_rate: 0.0
                total_iters: 1000
        precision:
            enabled: true
            loss_scaling_factor: dynamic
        loop:
            max_steps: 1000
        logging:
            log_steps: 100
    fit:
        train_dataloader:
            data_processor: AlphabetDataProcessor
            num_samples: 20000
            seq_length: 10
            batch_size: 32
            seed: 1
        val_dataloader: &id001
            data_processor: AlphabetDataProcessor
            num_samples: 2000
            seq_length: 10
            batch_size: 32
            seed: 1
    validate:
        val_dataloader: *id001
    validate_all:
        val_dataloaders: *id001
