# Copyright 2022 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# BERT-Base, MSL:128

trainer:
  init:
    backend:
      backend_type: CSX
    model_dir: ./model_dir
    seed: 1
    model:
      name: "bert"
      vocab_size: 30522
      hidden_size: 768
      num_hidden_layers: 12
      num_heads: 12
      filter_size: 3072
      encoder_nonlinearity: gelu   # {"gelu", "relu", "silu", "gelu_new"}
      pooler_nonlinearity: tanh
      dropout_rate: 0.1
      attention_dropout_rate: 0.1
      max_position_embeddings: 512
      layer_norm_epsilon: 1.0e-05
      mlm_loss_weight: 0.058
    optimizer:
      AdamW:
        weight_decay: 0.01
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            end_learning_rate: 0.0001767766952966369 # (sqrt(3200.0/256.0)/2)*0.0001
            total_iters: 3200
        - LinearLR:
            initial_learning_rate: 0.0001767766952966369 # (sqrt(3200.0/256.0)/2)*0.0001
            end_learning_rate: 0.0
            total_iters: 77600
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    loop:
      max_steps: 72000
      eval_frequency: 10000
      eval_steps: 220
    checkpoint:
      steps: 10000
      save_initial_checkpoint: true
    logging:
      log_steps: 1
  fit:
    train_dataloader:
      data_processor: BertCSVDynamicMaskDataProcessor
      data_dir: ./language/datasets/owt_pretraining_csv/train_512k_uncased_msl128/
      vocab_file: "$MODELZOO_ROOT/models/vocab/google_research_uncased_L-12_H-768_A-12.txt"
      max_sequence_length: 128
      max_predictions_per_seq: 20
      # The effective batch size, which is evenly divided across "num_csx" systems used for the run
      batch_size: 3200
      do_lower: true
      masked_lm_prob: 0.15
      shuffle: true
      shuffle_seed: 1
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader: &val_dataloader
      data_processor: BertCSVDynamicMaskDataProcessor
      data_dir: ./language/datasets/owt_pretraining_csv/val_uncased_msl128/
      vocab_file: ./language/models/bert/pretrained/google-research/uncased_L-12_H-768_A-12/vocab.txt
      max_sequence_length: 128
      max_predictions_per_seq: 20
      batch_size: 256
      do_lower: true
      masked_lm_prob: 0.15
      shuffle: false
      shuffle_seed: 1
      num_workers: 2
      prefetch_factor: 10
      persistent_workers: true
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
