# Copyright 2022 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# RoBERTa-Base, MSL:512

trainer:
  init:
    backend:
      backend_type: CSX
    model_dir: ./model_dir
    seed: 1
    model:
      name: "bert"
      disable_nsp: true # turn off NSP head
      mask_padding_in_positional_embed: true
      vocab_size: 28996
      hidden_size: 768
      num_hidden_layers: 12
      num_heads: 12
      filter_size: 3072
      encoder_nonlinearity: gelu # {"gelu", "relu", "silu", "gelu_new"}
      pooler_nonlinearity: tanh
      dropout_rate: 0.1
      attention_dropout_rate: 0.1
      max_position_embeddings: 512
      mlm_loss_weight: 0.019 # should be 0.058 if training with max seq length 128, 0.019 with 512
      layer_norm_epsilon: 1.0e-05
      fp16_type: cbfloat16
      mixed_precision: true
    optimizer:
      AdamW:
        correct_bias: true
        weight_decay: 0.01
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            end_learning_rate: 0.0001
            total_iters: 10000
        - LinearLR:
            initial_learning_rate: 0.0001
            end_learning_rate: 0.0
            total_iters: 1000000
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    loop:
      max_steps: 1000000
      eval_frequency: 5000
      eval_steps: 240
    checkpoint:
      steps: 5000
      save_initial_checkpoint: true
    logging:
      log_steps: 100
  fit:
    train_dataloader:
      data_processor: BertCSVDynamicMaskDataProcessor
      data_dir: ./language/datasets/wikicorpus_csv/train_cased_msl512_mlm_only_unmasked
      vocab_file: "$MODELZOO_ROOT/models/vocab/google_research_cased_L-12_H-768_A-12.txt"
      max_sequence_length: 512
      max_predictions_per_seq: 80
      shuffle: true
      shuffle_seed: 1
      do_lower: false
      # The effective batch size, which is evenly divided across "num_csx" systems used for the run
      batch_size: 256 # for GPU(16GB) set batch_size 8
      # 8 * 32 = 256 with grad_accum_steps: 32
      num_workers: 8
    val_dataloader: &val_dataloader
      data_processor: BertCSVDynamicMaskDataProcessor
      data_dir: ./language/datasets/wikicorpus_csv/val_cased_msl512_mlm_only_unmasked
      vocab_file: ./language/models/bert/pretrained/google-research/cased_L-12_H-768_A-12/vocab.txt
      max_sequence_length: 512
      max_predictions_per_seq: 80
      shuffle: false
      shuffle_seed: 1
      do_lower: false
      batch_size: 256
      num_workers: 3
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
