# Copyright 2022 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# GPT-2 small model (117M parameters)
# Works with CS-2 in weight streaming mode.

### Input
train_input:
    data_processor: "GptTfRecordsProcessor"
    data_dir: 
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/0"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/1"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/2"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/3"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/4"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/5"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/6"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/7"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/8"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/9"
    vocab_size: 50257
    max_sequence_length: 2048
    shuffle: True
    repeat: True
    batch_size: 32

eval_input:
    data_processor: "GptTfRecordsProcessor"
    data_dir: "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/val_msl2048"
    vocab_size: 50257
    max_sequence_length: 2048
    shuffle: True
    repeat: False
    batch_size: 32

### Model
model:
    # Embedding
    hidden_size: 768
    use_position_embedding: True
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 2048

    # Encoder
    num_hidden_layers: 12
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5

    # Encoder - Attention
    num_heads: 12
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: True

    # Encoder - ffn
    filter_size: 3072
    nonlinearity: "gelu"
    use_ffn_bias: True

    # Task-specific
    loss_scaling: "num_tokens"

    # Cerebras parameters
    mixed_precision: True
    boundary_casting: False
    tf_summary: False
    use_vsl: False

### Optimization
optimizer:
    optimizer_type: "adamw"
    epsilon: 1.0e-5
    weight_decay_rate: 0.01
    max_gradient_norm: 1.0
    learning_rate: 2.8e-4
    loss_scaling_factor: "dynamic"
    log_summaries: True

### Runtime
runconfig:
    max_steps: 100000
    save_summary_steps: 100
    save_checkpoints_steps: 10000
    keep_checkpoint_max: 2
    enable_distributed: False

