trainer:
  init:
    backend:
      backend_type: CSX
    seed: 1
    model:
      name: "jais"
      attention_dropout_rate: 0.0
      attention_kernel: optimized_beta
      attention_softmax_fp32: false
      attention_type: scaled_dot_product
      boundary_casting: false
      dropout_rate: 0.0
      embedding_initializer:
        a: -0.146
        b: 0.146
        mean: 0.0
        name: truncated_normal
        std: 0.073
      embeddings_scale: 14.6
      filter_size: 19114
      hidden_size: 7168
      initializer:
        a: -0.146
        b: 0.146
        mean: 0.0
        name: truncated_normal
        std: 0.073
      layer_norm_epsilon: 1.0e-05
      loss_scaling: batch_size
      loss_weight: 0.000589014090626433
      max_position_embeddings: 8192
      nonlinearity: swiglu
      num_heads: 56
      num_hidden_layers: 48
      output_layer_initializer:
        a: -0.146
        b: 0.146
        mean: 0.0
        name: truncated_normal
        std: 0.073
      mup_base_filter_size: 682.6428571
      mup_base_hidden_size: 256
      output_logits_alpha: 2.22
      position_embedding_type: alibi
      scale_qk_dot_by_d: true
      share_embedding_weights: true
      use_bias_in_output: false
      use_ffn_bias: true
      use_ffn_bias_in_attention: true
      use_projection_bias_in_attention: true
      vocab_size: 84992
    optimizer:
      AdamW:
        betas:
        - 0.9
        - 0.95
        correct_bias: true
        eps: 8.0e-10
        weight_decay: 0.1
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            end_learning_rate: 0.0016
            initial_learning_rate: 0.0
            total_iters: 400
        - LinearLR:
            end_learning_rate: 0.00016
            initial_learning_rate: 0.0016
            total_iters: 6857
    precision:
      enabled: true
      fp16_type: cbfloat16
      precision_opt_level: 1
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
      log_loss_scale: true
    loop:
      max_steps: 7257
      eval_frequency: 1210
    checkpoint:
      steps: 1210
      save_initial_checkpoint: false
    logging:
      log_steps: 1
    callbacks:
    - ScopedTrainFlags:
        csx.performance.micro_batch_size: 11
    - ComputeNorm: {}
  fit:
    train_dataloader:
      batch_size: 132
      data_dir: ./language/datasets/SlimPajama/train_shuffled_msl8192/
      data_processor: GptHDF5MapDataProcessor
      num_workers: 1
      persistent_workers: true
      prefetch_factor: 10
      shuffle: false
      shuffle_seed: 1
      use_worker_cache: false
    val_dataloader: &val_dataloader
      batch_size: 8
      data_dir: ./language/datasets/SlimPajama/val_msl8192/
      data_processor: GptHDF5MapDataProcessor
      num_workers: 1
      shuffle: false
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
