trainer:
  init:
    seed: 0
    backend:
      backend_type: CSX
      cluster_config:
        max_wgt_servers: 24
        num_workers_per_csx: 1
    model:
      name: "gpt3"
      # Embedding
      hidden_size: 6144
      vocab_size: 50257
      position_embedding_type: learned
      share_embedding_weights: true
      max_position_embeddings: 2048
      # Encoder
      num_hidden_layers: 44
      dropout_rate: 0.0
      layer_norm_epsilon: 1.0e-05  # change to 1.0e-12 for single precision training
      # Encoder - Attention
      num_heads: 64
      attention_type: scaled_dot_product
      attention_dropout_rate: 0.0
      use_projection_bias_in_attention: true
      use_ffn_bias_in_attention: true
      embedding_initializer:
        name: truncated_normal
        mean: 0.0
        std: 0.02
      initializer:
        name: truncated_normal
        mean: 0.0
        std: 0.02
      output_layer_initializer:
        name: truncated_normal
        mean: 0.0
        std: 0.0021320071635561044
      filter_size: 24576
      nonlinearity: gelu
      use_ffn_bias: true
      use_bias_in_output: false
      loss_scaling: num_tokens
      loss_weight: 1.0
      mixed_precision: true
      boundary_casting: false
      fp16_type: cbfloat16
    optimizer:
      adamw:
        betas:
        - 0.9
        - 0.95
        eps: 1.0e-08
        correct_bias: true
        weight_decay: 0.01
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            end_learning_rate: 5.5e-05
            total_iters: 649
        - CosineDecayLR:
            initial_learning_rate: 5.5e-05
            end_learning_rate: 5.5e-06
            total_iters: 170129
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      initial_loss_scale: 2147483648.0
      max_loss_scale: 2147483648.0
      max_gradient_norm: 1.0
      log_loss_scale: true
    loop:
      max_steps: 170778
      eval_frequency: 5000
      eval_steps: 2409
    checkpoint:
      steps: 5000
      save_initial_checkpoint: true
    logging:
      log_steps: 1
    callbacks:
    - ComputeNorm: {}
    - KeepNCheckpoints:
        n: 21
  fit:
    train_dataloader:
      data_processor: GptHDF5MapDataProcessor
      data_dir:
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/0/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/1/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/2/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/3/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/4/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/5/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/6/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/7/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/8/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/9/
      shuffle: false  # data is expected to be shuffled during preprocessing
      shuffle_seed: 256
      # The effective batch size, which is evenly divided across "num_csx" systems used for the run
      batch_size: 77
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader: &val_dataloader
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./language/datasets/pile_original/hdf5_dataset/val_msl2048/
      shuffle: false
      batch_size: 77
      num_workers: 8
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
