# Copyright 2022 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#BERT-Large, max seq length 512

### Input
train_input:
    data_processor: "BertTfRecordsProcessor"
    data_dir: "./language/datasets/owt_pretraining/train_512k_uncased_msl512"
    vocab_file: "../../vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 512
    max_predictions_per_seq: 80  # maximum number of masked LM predictions per sequence
    batch_size: 256
    scale_mlm_weights: True
    buckets: [87, 158, 239, 325, 415] # should only be used with batch size 256

eval_input:
    data_processor: "BertTfRecordsProcessor"
    data_dir: "./language/datasets/owt_pretraining/val_uncased_msl512"
    vocab_file: "../../vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 512
    max_predictions_per_seq: 80  # maximum number of masked LM predictions per sequence
    batch_size: 256
    scale_mlm_weights: True

model:
    # Embedding
    hidden_size: 1024
    use_position_embedding: True
    use_segment_embedding: True
    position_embedding_type: "learned" # {"learned", "fixed"}
    max_position_embeddings: 512
    share_embedding_weights: True

    # Encoder
    num_hidden_layers: 24
    dropout_rate: 0.1
    layer_norm_epsilon: 1.0e-5

    # Encoder - Attention
    num_heads: 16
    attention_dropout_rate: 0.1

    # Encoder - ffn
    filter_size: 4096
    encoder_nonlinearity: "gelu"
    use_ffn_bias: True

    use_vsl: True
    mixed_precision: True
    boundary_casting: False
    tf_summary: False

### Optimization
optimizer:
    optimizer_type: "adamw" # {"sgd", "momentum", "adam", "adamw"}
    weight_decay_rate: 0.01
    epsilon: 1.0e-6
    max_gradient_norm: 1.0
    disable_lr_steps_reset: True
    learning_rate:
        - steps: 10000
          scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 0.0001
        - scheduler: "Linear"
          initial_learning_rate: 0.0001
          end_learning_rate: 0.0
          steps: 1000000
    loss_scaling_factor: "dynamic"

runconfig:
    save_summary_steps: 100
    save_checkpoints_steps: 10000
    keep_checkpoint_max: 0
    max_steps: 1000000
    enable_distributed: False
    model_dir: "model_dir"
    cs_ip:
    mode: "train"
    multireplica: False
