# A 6.7B parameter Cerebras-GPT model configuration intended to run on a cluster
# of 8 CS-2s dense.

# This config replicates the results in: https://www.cerebras.net/blog/accelerating-llm-training-with-variable-sparse-pre-training-and-dense-fine-tuning/

trainer:
  init:
    backend:
      backend_type: CSX
    model:
      name: "gpt3"
      # Embedding
      hidden_size: 4096
      position_embedding_type: learned
      share_embedding_weights: true
      max_position_embeddings: 2048
      vocab_size: 50257
      # Decoder
      num_hidden_layers: 32
      dropout_rate: 0.0
      layer_norm_epsilon: 1.0e-05
      # Decoder - Attention
      num_heads: 32
      attention_type: scaled_dot_product
      attention_dropout_rate: 0.0
      use_projection_bias_in_attention: true
      use_ffn_bias_in_attention: true
      # Decoder - ffn
      filter_size: 16384
      nonlinearity: gelu
      use_ffn_bias: true
      embedding_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.02
        a: -0.04
        b: 0.04
      initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.02
        a: -0.04
        b: 0.04
      output_layer_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.0025
        a: -0.005
        b: 0.005
      # Task-specific
      loss_scaling: num_tokens
      loss_weight: 1.0
      use_bias_in_output: false
    optimizer:
      AdamW:
        betas:
        - 0.9
        - 0.95
        eps: 1.0e-09
        weight_decay: 0.1
        correct_bias: true
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            end_learning_rate: 0.00036
            total_iters: 938
        - LinearLR:
            initial_learning_rate: 0.00036
            end_learning_rate: 1.2e-05
            total_iters: 8441
    precision:
      # Cerebras parameters
      enabled: true
      fp16_type: cbfloat16
      precision_opt_level: 1
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
      log_loss_scale: true
    loop:
      max_steps: 9379
      eval_frequency: 1000
      eval_steps: 2854
    checkpoint:
      steps: 1000
      save_initial_checkpoint: false
    logging:
      log_steps: 10
    callbacks:
    - ComputeNorm: {}
  fit:
    train_dataloader:
      data_processor: GptHDF5MapDataProcessor
      data_dir:
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/0/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/1/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/2/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/3/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/4/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/5/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/6/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/7/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/8/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/9/
      shuffle: true
      shuffle_seed: 0
      # The effective batch size, which is evenly divided across "num_csx" systems used for the run
      batch_size: 1040  # 1040 global = (65 micro)*(8 csx)*(2 grad accum step)
      num_workers: 1
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader: &val_dataloader
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./language/datasets/pile_original/hdf5_dataset/val_msl2048/
      batch_size: 65
      shuffle: false
      num_workers: 1
      prefetch_factor: 10
      persistent_workers: true
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
