# Santacoder model, 1B parameters, max_seq_length 2048
# Based on: https://arxiv.org/pdf/2301.03988.pdf

trainer:
  init:
    backend:
      backend_type: CSX
    seed: 1
    model:
      name: "santacoder"
      # Embedding
      vocab_size: 49280
      position_embedding_type: learned
      embedding_dropout_rate: 0.1
      share_embedding_weights: true  # no config default values, HF uses tie_weights as default
      # Decoder Block
      hidden_size: 2048
      filter_size: 8192
      num_heads: 16
      num_hidden_layers: 24
      max_position_embeddings: 2048
      attention_module: multiquery_attention
      attention_type: scaled_dot_product
      attention_softmax_fp32: true
      extra_attention_params:
        num_kv_groups: 1
      use_projection_bias_in_attention: true
      use_ffn_bias_in_attention: true
      use_ffn_bias: true
      nonlinearity: gelu
      attention_dropout_rate: 0.1
      dropout_rate: 0.1
      layer_norm_epsilon: 1.0e-05
      use_bias_in_output: false
      initializer_range: 0.02
    optimizer:
      Adam:
        betas:
        - 0.9
        - 0.95
        eps: 1.0e-08
        weight_decay: 0.1
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            total_iters: 12000
            initial_learning_rate: 0.0
            end_learning_rate: 0.0002
        - CosineDecayLR:
            initial_learning_rate: 0.0002
            total_iters: 588000
            end_learning_rate: 0.0
    precision:
      enabled: true
      fp16_type: cbfloat16
      precision_opt_level: 0
      loss_scaling_factor: dynamic
    loop:
      max_steps: 600000
      eval_frequency: 5000
    checkpoint:
      steps: 5000
    logging:
      log_steps: 100
  fit:
    train_dataloader:
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./shuffled/santacoder_data_test/val
      shuffle: false
      shuffle_seed: 1
      batch_size: 192
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader: &val_dataloader
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./shuffled/santacoder_data_test/test
      shuffle: false
      shuffle_seed: 1
      batch_size: 192
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
